In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
points= np.genfromtxt('2d_pointcloud.txt', delimiter=' ', skip_header=1)
print(points.shape)
print(points[:10])

(721, 4)
[[1.093610e-16 1.786000e+00 0.000000e+00 1.606775e-02]
 [7.757964e-03 1.777983e+00 0.000000e+00 1.599145e-02]
 [1.554196e-02 1.780932e+00 0.000000e+00 1.611353e-02]
 [2.332566e-02 1.781847e+00 0.000000e+00 1.609827e-02]
 [3.130962e-02 1.793727e+00 0.000000e+00 1.651026e-02]
 [4.020483e-02 1.842561e+00 0.000000e+00 1.661707e-02]
 [4.994562e-02 1.907346e+00 0.000000e+00 1.742580e-02]
 [5.906149e-02 1.933098e+00 0.000000e+00 1.736477e-02]
 [6.857751e-02 1.963803e+00 0.000000e+00 1.646448e-02]
 [7.793073e-02 1.983470e+00 0.000000e+00 1.701381e-02]]


In [3]:
# Make it smaller for testing
# points= points[:50]

In [4]:
# Threshold distance value to decide if the point is on the plane 
threshold= 0.005

n= len(points)
# outliner_count_min= n
D_min= 100
result= (-1, -1)

In [5]:
for i in range(n):
    for j in range(i + 1, n):
        p1= points[i]
        p2= points[j]
#         outliner_count= 0
        D= 0
        for p3 in points:            
            p1_2d= np.array([p1[0], p1[1]])
            p2_2d= np.array([p2[0], p2[1]])
            p3_2d= np.array([p3[0], p3[1]])
            d= np.linalg.norm(np.cross(p2_2d - p1_2d, p1_2d - p3_2d)) / np.linalg.norm(p2_2d - p1_2d)
#             print(d)
            D+= d
#             if d > threshold:
#                 outliner_count+= 1
#         print(outliner_count)
#         if outliner_count < outliner_count_min:
#             result= (p1, p2)
#             outliner_count_min= outliner_count
        if D < D_min:
            result= (p1, p2)
            D_min= D
# print("Min outliner count:", outliner_count_min)
print("D min: ", D_min)
result

KeyboardInterrupt: 

In [ ]:
p1= result[0]
p2= result[1]
p1_2d= np.array([p1[0], p1[1]])
p2_2d= np.array([p2[0], p2[1]])

In [ ]:
points_del= np.delete(points, 2, axis=1)
points_del= np.delete(points_del, 2, axis=1)
print(points_del[:10])

In [ ]:
plt.plot(points_del , 'o', color='black')
plt.plot(p1_2d, p2_2d)

In [ ]:
def is_on_ground_plane(point, threshold):
    point= np.array([point[0], point[1]])
    d= np.linalg.norm(np.cross(p2_2d - p1_2d, p1_2d - point)) / np.linalg.norm(p2_2d - p1_2d)
    if d < threshold:
        return True
    return False

In [ ]:
p1= np.array([1.09361e-16, 1.786, 0, 0.01606775])
p2= np.array([0.4115986, -5.538728, 0, 0.01622034])

print("p1 is on the ground plane: ", is_on_ground_plane(p1, 0.05))
print("p2 is on the ground plane: ", is_on_ground_plane(p2, 0.05))